### ISSUE TITLE
Create randomised data

### ISSUE THREAD

**Issue by sebastian-c** [sebastian-c/overflow#10]
A frequent task on SO is to create a random dataset. This is somewhat more difficult that making a matrix of random numbers as it is generally required that each of the columns be of specific types. A function to do this was [developed and demonstrated](http://trinkerrstuff.wordpress.com/2012/05/02/function-to-generate-a-random-data-set/) by Tyler Rinker.

Perhaps a general function which produces a range of different data types or a suite of functions to produce different types of data.

It is noted that this function will allow the answering of questions which would be hard to answer because they lack a reproducible example.

**Comment by mrdwab** [comment]
In particular, the function needs to be easy to scale in terms of the number of rows, number of columns, and number of factor levels being generated, since this will facilitate realistic benchmarking exercises. I think that the function from @trinker only supports modifying the number of rows in the dataset.

**Comment by trinker** [comment]
@mrdwab You are correct.  The function is supposed to be a one sized fits all (i.e. there's time series, categorical, ratio etc.).

**Comment by sebastian-c** [comment]
At the moment I'm working on getting this to work. I've already got a preliminary version which grabs the functions from an internal environment (rather like Yihui Xie's animation package). I've used Tyler Rinker's functions to test with and so far it seems to go ok:

``` r
sorandf <- function(rows=10L, cols=c("race", "gender", "age"), names=make.names(cols)){

  setNames(as.data.frame(lapply(cols, function(x) get(x, envir=.so.env)(rows))), names)

}

.so.env <- as.environment(list(id = function(n) paste0("ID.", 1:n), 
                group = function(n) sample(c("control", "treat"), n, replace = TRUE),
                hs.grad = function(n) sample(c("yes", "no"), n, replace = TRUE), 
                race = function(n) sample(c("black", "white", "asian"), n, 
                              replace = TRUE, prob=c(.25, .5, .25)), 
                gender = function(n) sample(c("male", "female"), n, replace = TRUE), 
                age = function(n) sample(18:40, n, replace = TRUE),
                m.status = function(n) sample(c("never", "married", "divorced", "widowed"), 
                                  n, replace = TRUE, prob=c(.25, .4, .3, .05)), 
                political = function(n) sample(c("democrat", "republican", 
                                     "independent", "other"), n, replace= TRUE, 
                                   prob=c(.35, .35, .20, .1)),
                n.kids = function(n) rpois(n, 1.5), 
                income = function(n) sample(c(seq(0, 30000, by=1000), 
                                  seq(0, 150000, by=1000)), n, replace=TRUE),
                score = function(n) rnorm(n)
                ))
```

**Comment by sebastian-c** [comment]
Hello all, I've been getting back into shaping this package. I've added this function to a separate branch in the repository (sebastian-c/overflow@43276c5) and I'll be adding it to the main one soon.

**Comment by sebastian-c** [comment]
Added this function to the master branch. Will be adding a way to create NAs soon (#21).
