### ISSUE TITLE
A quick way to grab data/functions

### ISSUE THREAD

**Issue by trinker** [sebastian-c/overflow#11]
I made a dput2 function that grabs function/data and pastes to clipboard/prints console for easy transfer.  You may want to consider something like this:

http://www.talkstats.com/showthread.php/18603-Share-your-functions-amp-code?p=97845&viewfull=1#post97845

**Comment by sebastian-c** [comment]
Good idea. One of the ideas I had when making this package was tools for asking questions as well as answering them. Would it be sensible to add a `head` argument, so it doesn't have to dput your entire data, optionally only the first n elements of it, or is it a better idea to let the user do the subsetting themselves?

**Comment by trinker** [comment]
Yes certainly or `rows` so as to specify rows, though `head` could be used inside of the function.  Probably 6 rows is a reasonable default.  I'd then set that if this to `NULL` and if it's null the entire input is used (useful for functions over dataframes).  It is a good concept but needs to be tweaked.  i think it would be nice to direct people to use this rather than saying use `dput(head(DATASET))`

Love the idea by the way.  I had a similar one and have a few functions that I thought about getting together but just always lacked the motivation.
