### ISSUE TITLE
Functions are cumbersome to type

### ISSUE THREAD

**Issue by sebastian-c** [sebastian-c/overflow#18]
At the moment, I'm finding I'm making a few typos with these function due to the switch between uppercase and lowercase letters.

I think the core idea of this package is that the function are _convenient_, that is to say they're not going to be used in programming, but on the fly, so they should be as quick and easy to use as possible.

In light of this, I'm proposing the following changes:
- Making all functions lowercase
- All functions with SO will have it placed at the beginning. This gives a consistent naming convention and also makes it easy to find oveRflow functions with tab completion.
  For example, `readSO` will become `soread`. 

Finally, I'm proposing changing the package name from `oveRflow` to `overflow` just to make it easy to use. I think making these changes early is the best time for them to be made.

**Comment by mrdwab** [comment]
You don't want to go the underscore route? :)

I agree though. My original version of `readSO` was named `read.so`, which I still find easier to type, and I almost always have to delete and retype the capital R in `oveRflow` because of muscle memory.

:+1:

**Comment by sebastian-c** [comment]
I do have the one install packages (tmp_install_packages) function with underscores. I had a dearth of imagination that day and could not think of a sensible way to abbreviate it. If you or @juba can think of one, now would be a great time to rename some functions.

The only reason I use underscores is so there's no confusion with S3 methods. I do see now that full stops are more convenient than underscores for typing (no need to use <kbd>shift</kbd>).

**Comment by sebastian-c** [comment]
Fixed in 2de878d3ce8becb5de1221dfbf4f7afa7ecbb4f4. All user visible functions are prefixed with 'so' and the package has been renamed to 'overflow'.
