### ISSUE TITLE
overflow documentation

### ISSUE THREAD

**Issue by Jazzurro** [sebastian-c/overflow#25]
I have been looking for information of this package, but it seems to me that there is no much available out there. I have been using soread() for some time. But, it seems to me that there are more functions. For example, I see sorandf(). But, I do not know how I can use it. I personally think that it would be great if there is a documentation of this package. Such a document will definitely help many SO users given there are many malformed questions.

**Comment by sebastian-c** [comment]
I know this seems like a silly response, but I assume you've looked at the documentation for `sorandf` by typing `?sorandf`. I admit that I was planning to add more functions to that (although it's possible to add them on one's own now. Is there anything specific that was difficult?
