### ISSUE TITLE
Is there a way to submit a question on stackoverflow with overflow package?

### ISSUE THREAD

**Issue by MarcinKosinski** [sebastian-c/overflow#27]
I've seen `overflow` package in this answer to [SO question](http://meta.stackexchange.com/questions/174972/stackoverflow-api-for-r). There are also links to other R packages that communicate with stackoverflow API. Did you consider using `overflow` to submit a question on stackoverflow from R console?

**Comment by sebastian-c** [comment]
I've thought about using the SO API, but I don't think that R is necessarily the best text editor. Are you perhaps suggesting being able to send an Rmd file as a question or answer?

**Comment by MarcinKosinski** [comment]
Yes, that would be great - `.Rmd` file.
I don't say R is the best text editor, but R+RStudio is the only software I know :)

**Comment by mrdwab** [comment]
@MarcinKosinski , did you also check out "stackr" by @dgrtwo? I believe that uses the API.

**Comment by MarcinKosinski** [comment]
[https://github.com/dgrtwo/stackr/issues/4](https://github.com/dgrtwo/stackr/issues/4) yep I asked him also :)
